spring.application.name=estudiantes
#en memoria
spring.datasource.url=jdbc:h2:mem:estudiantesdb
#para guardar la bd en un archivo de forma persistente es pago jdbc:h2:file:./data/db

server.port=8081

spring.h2.console.enabled=true
spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.url=jdbc:h2:~/proyecto
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#create-drop

#conf para adaptar sql a esa base
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

